import { Metadata } from "next";
import Link from "next/link";

import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body>
        <Header />
        <div>
          <Link href="/account">Account Page</Link>
          <br />
          <Link href="/login">Login Page</Link>
          <br />
          <Link href="/cart">Cart Page</Link>
          <br />
        </div>
        <main>{children}</main>
      </body>
    </html>
  );
};

export default RootLayout;
